import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CodeBlock, TerminalBlock } from "@/components/code-block";
import { Callout } from "@/components/callout";

export const metadata: Metadata = { title: "Creating a Generator" };

const folderStructure = `my-generator/
  generator.json       ← required manifest
  templates/           ← your template files
    index.tsx.hbs
    styles.css.hbs
    README.md.hbs
  scripts/             ← optional post-install scripts
    setup.sh`;

const minimalGenerator = `{
  "name": "acme/hello-world",
  "type": "feature",
  "actions": [
    {
      "type": "template",
      "source": "templates/hello.ts.hbs",
      "target": "src/hello.ts"
    }
  ]
}`;

const helloTemplate = `// Generated by xo — acme/hello-world
export function hello(name: string): string {
  return \`Hello, {{name}}!\`;
}`;

const fullGenerator = `{
  "name": "acme/react-component",
  "type": "feature",
  "requires": ["acme/react-setup"],
  "conflicts": ["acme/vue-setup"],
  "detects": [
    { "signal": "pkg:react", "exists": true },
    { "signal": "language", "equals": "typescript" }
  ],
  "prompts": [
    {
      "name": "componentName",
      "type": "input",
      "message": "What is the component name?"
    },
    {
      "name": "componentType",
      "type": "select",
      "message": "Component type?",
      "choices": ["client", "server", "shared"]
    },
    {
      "name": "withStories",
      "type": "confirm",
      "message": "Add a Storybook story?",
      "when": "componentType === 'client' || componentType === 'shared'"
    },
    {
      "name": "withTests",
      "type": "confirm",
      "message": "Add a test file?"
    }
  ],
  "actions": [
    {
      "type": "template",
      "source": "templates/component.tsx.hbs",
      "target": "src/components/{{pascalCase componentName}}/index.tsx"
    },
    {
      "type": "template",
      "source": "templates/stories.tsx.hbs",
      "target": "src/components/{{pascalCase componentName}}/{{pascalCase componentName}}.stories.tsx",
      "if": "withStories"
    },
    {
      "type": "template",
      "source": "templates/test.tsx.hbs",
      "target": "src/components/{{pascalCase componentName}}/index.test.tsx",
      "if": "withTests"
    },
    {
      "type": "inject",
      "target": "src/components/index.ts",
      "after": "// components",
      "content": "export { {{pascalCase componentName}} } from './{{pascalCase componentName}}';"
    }
  ]
}`;

const componentTemplate = `"use client";

import type { ComponentProps } from "react";

interface {{pascalCase componentName}}Props extends ComponentProps<"div"> {
  // your props here
}

export function {{pascalCase componentName}}({ className, ...props }: {{pascalCase componentName}}Props) {
  return (
    <div className={className} {...props}>
      {{pascalCase componentName}}
    </div>
  );
}`;

export default function CreatingGeneratorsPage() {
  return (
    <article className="max-w-3xl space-y-10">
      <div>
        <p className="mb-1 text-sm font-medium text-primary">Building Generators</p>
        <h1 className="mb-3 text-3xl font-bold">Creating a Generator</h1>
        <p className="text-base leading-relaxed text-muted-foreground">
          A generator is a folder with a <code>generator.json</code> manifest and any template files
          it references. This page walks through everything from a minimal example to a production-ready generator.
        </p>
      </div>

      {/* Folder structure */}
      <section className="space-y-4">
        <h2 className="text-xl font-semibold">Folder structure</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          There is no required file organization beyond <code>generator.json</code> at the root.
        </p>
        <CodeBlock code={folderStructure} lang="text" />
        <p className="text-sm text-muted-foreground">
          Template files can use any extension — <code>.hbs</code> is conventional but not required.
          xo renders any file referenced by a <code>template</code> action.
        </p>
      </section>

      {/* Minimal example */}
      <section className="space-y-4">
        <h2 className="text-xl font-semibold">Minimal example</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          The smallest valid generator needs only <code>name</code>, <code>type</code>, and at least one action.
        </p>
        <CodeBlock code={minimalGenerator} filename="generator.json" lang="json" />
        <CodeBlock code={helloTemplate} filename="templates/hello.ts.hbs" lang="handlebars" />
        <Callout variant="tip" title="Variables in template files">
          Inside <code>.hbs</code> files, use <code>{"{{variableName}}"}</code> — values come from
          prompt answers and project signals.
        </Callout>
      </section>

      {/* generator.json reference */}
      <section className="space-y-4">
        <h2 className="text-xl font-semibold">generator.json reference</h2>
        <div className="overflow-x-auto rounded-lg border border-border">
          <table className="w-full text-sm">
            <thead className="border-b border-border bg-muted/50">
              <tr>
                {["Field", "Type", "Required", "Description"].map((h) => (
                  <th key={h} className="px-4 py-2.5 text-left text-xs font-semibold">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {[
                ["name", "string", "Yes", "Unique name, conventionally owner/repo"],
                ["type", '"project" | "feature"', "Yes", "project = new scaffold, feature = adds to existing"],
                ["requires", "string[]", "No", "Generators that must already be applied"],
                ["conflicts", "string[]", "No", "Generators that must NOT be present"],
                ["provides", "string[]", "No", "Logical capabilities this generator declares"],
                ["detects", "DetectRule[]", "No", "Signal rules that must match before running"],
                ["prompts", "Prompt[]", "No", "Interactive questions asked before running actions"],
                ["actions", "Action[]", "No", "Ordered list of file/command operations"],
              ].map(([field, type, req, desc]) => (
                <tr key={field} className="hover:bg-muted/30">
                  <td className="px-4 py-2.5 font-mono text-xs text-primary">{field}</td>
                  <td className="px-4 py-2.5 font-mono text-xs text-muted-foreground">{type}</td>
                  <td className="px-4 py-2.5 text-xs">{req}</td>
                  <td className="px-4 py-2.5 text-xs text-muted-foreground">{desc}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* Prompts */}
      <section className="space-y-4">
        <h2 className="text-xl font-semibold">Defining prompts</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          Prompts collect user input before actions run. Answers become template variables available in all
          action fields and template files.
        </p>
        <div className="overflow-x-auto rounded-lg border border-border">
          <table className="w-full text-sm">
            <thead className="border-b border-border bg-muted/50">
              <tr>
                {["Type", "Renders as", "Extra fields"].map((h) => (
                  <th key={h} className="px-4 py-2.5 text-left text-xs font-semibold">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {[
                ["input", "Free-text field", "—"],
                ["confirm", "Yes / No question", "—"],
                ["select", "Single-choice list", "choices: string[]"],
                ["multiselect", "Multi-choice checkboxes", "choices: string[]"],
              ].map(([t, r, e]) => (
                <tr key={t} className="hover:bg-muted/30">
                  <td className="px-4 py-2.5 font-mono text-xs text-primary">{t}</td>
                  <td className="px-4 py-2.5 text-xs text-muted-foreground">{r}</td>
                  <td className="px-4 py-2.5 font-mono text-xs text-muted-foreground">{e}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p className="text-sm text-muted-foreground">
          Use the <code>when</code> field to conditionally show a prompt based on prior answers or signals:
        </p>
        <CodeBlock
          code={`{
  "name": "withTests",
  "type": "confirm",
  "message": "Add a test file?",
  "when": "componentType !== 'server'"
}`}
          lang="json"
        />
      </section>

      {/* Handlebars */}
      <section className="space-y-4">
        <h2 className="text-xl font-semibold">Handlebars templates</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          Template files use Handlebars syntax. Variables come from prompt answers and project signals.
          Helpers are also available in <code>target</code> path values.
        </p>
        <CodeBlock code={componentTemplate} filename="templates/component.tsx.hbs" lang="handlebars" />
        <div className="overflow-x-auto rounded-lg border border-border">
          <table className="w-full text-sm">
            <thead className="border-b border-border bg-muted/50">
              <tr>
                {["Helper", "Input", "Output"].map((h) => (
                  <th key={h} className="px-4 py-2.5 text-left text-xs font-semibold">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {[
                ["pascalCase", "my-component", "MyComponent"],
                ["camelCase", "my-component", "myComponent"],
                ["kebabCase", "MyComponent", "my-component"],
                ["snakeCase", "MyComponent", "my_component"],
                ["capitalize", "hello world", "Hello world"],
                ["eq / ne", "{{#if (eq a b)}}", "boolean equal / not-equal"],
                ["or / and", "{{#if (or a b)}}", "logical or / and"],
              ].map(([h, i, o]) => (
                <tr key={h} className="hover:bg-muted/30">
                  <td className="px-4 py-2.5 font-mono text-xs text-primary">{h}</td>
                  <td className="px-4 py-2.5 font-mono text-xs text-muted-foreground">{i}</td>
                  <td className="px-4 py-2.5 font-mono text-xs">{o}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* Detect rules */}
      <section className="space-y-4">
        <h2 className="text-xl font-semibold">Detect rules</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          Use <code>detects</code> to ensure your generator only runs in compatible projects.
          All rules are ANDed — every one must pass.
        </p>
        <CodeBlock
          code={`"detects": [
  { "signal": "pkg:react",  "exists": true },
  { "signal": "language",   "equals": "typescript" },
  { "signal": "framework",  "matches": "^(react|nextjs)$" }
]`}
          lang="json"
        />
        <p className="text-sm text-muted-foreground">
          See the{" "}
          <Link href="/docs/signals" className="font-medium text-primary hover:underline">
            Signals Reference
          </Link>{" "}
          for the full list of available signals.
        </p>
      </section>

      {/* Full example */}
      <section className="space-y-4">
        <h2 className="text-xl font-semibold">Full working example</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          A complete generator with prompts, conditional actions, detects, requires, and conflicts:
        </p>
        <CodeBlock code={fullGenerator} filename="generator.json" lang="json" />
        <Callout variant="info" title="The if field">
          Every action supports an <code>if</code> field — a JavaScript expression evaluated against
          the merged context of signals + prompt answers. The action is skipped when falsy.
        </Callout>
      </section>

      {/* Publishing */}
      <section className="space-y-4">
        <h2 className="text-xl font-semibold">Publishing to GitHub</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          Push your generator to any public GitHub repo — no registry account required.
        </p>
        <TerminalBlock
          commands={[
            "git init && git add .",
            'git commit -m "feat: react-component generator"',
            "git remote add origin git@github.com:acme/react-component.git",
            "git push -u origin main",
          ]}
        />
        <p className="text-sm text-muted-foreground">Users then run:</p>
        <TerminalBlock commands={["xo add acme/react-component"]} />
        <p className="text-sm text-muted-foreground">
          For a generator in a subdirectory, use <code>owner/repo/subpath</code>:
        </p>
        <TerminalBlock commands={["xo add acme/generators/react-component"]} />
        <Callout variant="tip" title="Private generators">
          Generators stored under <code>.xo/generators/</code> in your project are resolved locally
          first — no GitHub fetch needed.
        </Callout>
      </section>

      <div className="flex gap-4 pt-2">
        <Button asChild variant="link" className="h-auto p-0 text-primary">
          <Link href="/docs/actions">
            Actions reference <ArrowRight className="h-3.5 w-3.5" />
          </Link>
        </Button>
        <Button asChild variant="link" className="h-auto p-0 text-primary">
          <Link href="/docs/signals">
            Signals reference <ArrowRight className="h-3.5 w-3.5" />
          </Link>
        </Button>
      </div>
    </article>
  );
}
